### ISSUE TITLE
Make QLineEdits more responsive

### ISSUE THREAD

**Issue by thekumi** [nqrduck/nqrduck-spectrometer#11]
Currently, storing a value requires pressing the Enter key at the end, which is super awkward. Consider switching from editingFinished to textEdited (https://doc.qt.io/qtforpython-6/PySide6/QtWidgets/QLineEdit.html#PySide6.QtWidgets.PySide6.QtWidgets.QLineEdit.textEdited)

**Comment by jupfi** [comment]
This has been implemented with cb5df0a9afe98db0be0068f5cb0fefed14601298
