### ISSUE TITLE
Move widget generation for Settings to individual classes

### ISSUE THREAD

**Issue by thekumi** [nqrduck/nqrduck-spectrometer#6]
Instead of generating the widget for the individual fields in the View (https://github.com/nqrduck/nqrduck-spectrometer/blob/cb5df0a9afe98db0be0068f5cb0fefed14601298/src/nqrduck_spectrometer/base_spectrometer_view.py#L56), move the logic to a `get_widget()` method on the individual Setting subclasses.

**Comment by jupfi** [comment]
Fixed with a39b4a1bc7119f38c739e65bc776c9e7384cfc5b
