### ISSUE TITLE
Add validation to form field widgets

### ISSUE THREAD

**Issue by thekumi** [nqrduck/nqrduck-spectrometer#7]
Currently, there seems to be no validation done on Setting fields. Add validators (https://doc.qt.io/qtforpython-6/PySide6/QtWidgets/QLineEdit.html#PySide6.QtWidgets.PySide6.QtWidgets.QLineEdit.setValidator) on the edit widgets for things like type checking. This is probably related to #5.

**Comment by thekumi** [comment]
For example, ensure that numeric fields can only contain numeric values.

**Comment by thekumi** [comment]
Allow defining maximum/minimum values for numeric settings

**Comment by jupfi** [comment]
This has been implemented with cb5df0a9afe98db0be0068f5cb0fefed14601298
